[build]
  command = "yarn build"
  functions = "dist/netlify-functions"
  publish = "public"

[template.environment]
  API_KEY = "API Key"
  EVENTPOP_ORGANIZER_ID = "Event Pop Organizer ID"
  EVENTPOP_EVENT_ID = "Event Pop Event ID"
  EVENTPOP_SESSION_ID = "Event Pop Session ID"
