[build]
  command = "yarn build"
  functions = "dist/netlify-functions"
  publish = "public"

[template.environment]
  API_KEY = "Lock down this API with an API key -- put in a random string here"
  EVENTPOP_ORGANIZER_ID = "0"
  EVENTPOP_USER_ID = "0"
  EVENTPOP_SESSION_ID = "Obtain this from the browser cookie named `_stampmein_session`"
